version: '3.4'

services:
  csharp_aspnetcore_dockerandsqlserver:
    image: ${DOCKER_REGISTRY-}csharpaspnetcoredockerandsqlserver
    build:
      context: .
      dockerfile: Dockerfile
  sqlservercontainer:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=abc123ABC123
    ports:
      - 21433:1433
  mysqlContainer:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=abc123 
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --general-log=1 --general-log-file=mysqlgeneral.log
    ports:
      - 11306:3306


